- name: Configure mysql-server (my.cnf)
  template:
    src: 'my.cnf.j2'
    dest: '{{ mysql_config_file }}'
    owner: root
    group: root
    mode: 0644
  notify: restart mysql

- name: Verify include directory exists
  file:
    path: '{{ mysql_config_include_dir }}'
    state: directory
    owner: root
    group: root
    mode: 0755
  when: mysql_config_include_files | length

- name: Copy my.cnf override files
  template:
    src: '{{ mysql_config_file_loop }}'
    dest: '{{ mysql_config_include_dir }}/{{ mysql_config_file_loop | basename }}'
    owner: root
    group: root
    mode: 0644
  with_items: '{{ mysql_config_include_files }}'
  loop_control:
    loop_var: mysql_config_file_loop
  notify: restart mysql
