- name: Ensure config dirs exist
  file:
    dest: '{{ mysql_config_dir_loop }}'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'
  with_items:
    - '{{ mysql_config_dir }}'
    - '{{ mysql_config_include_dir }}'
  loop_control:
    loop_var: mysql_config_dir_loop

- name: Configure percona-server
  template:
    src: '{{ mysql_config_file_loop }}.cnf.j2'
    dest: '{{ mysql_config_include_dir }}/{{ mysql_config_file_loop }}.cnf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  with_items:
    - client
    - mysqld
    - mysqld_safe
    - mysqldump
  loop_control:
    loop_var: mysql_config_file_loop
  notify: restart mysql

- include: 'apparmor.yml'
  when: mysql_datadir != '/var/lib/mysql'
