- name: Prevent mysql to start on install
  copy:
    content: |-
      #!/bin/sh
      exit 101
    dest: '/usr/sbin/policy-rc.d'
    owner: 'root'
    group: 'root'
    mode: '0755'
  changed_when: False

- name: Install the mysql packages
  apt:
    name: '{{ mysql_apt_package_loop }}'
    state: 'present'
    update_cache: 'yes'
  with_items: '{{ mysql_packages }}'
  loop_control:
    loop_var: mysql_apt_package_loop

- name: Remove policy-rc.d
  file:
    name: '/usr/sbin/policy-rc.d'
    state: 'absent'
  changed_when: False
