---
# tasks file for mysql

- include: '{{ item }}.yml'
  with_items:
    - 'requirements'
    - 'configure'
    - 'install'
    - '{{ mysql_init_system }}'
    - 'secure'
    - 'databases-users'
  tags:
    - mysql
