- name: Install required packages
  apt:
    name: '{{ mysql_apt_package_loop }}'
  with_items: '{{ mysql_required_packages }}'
  loop_control:
    loop_var: mysql_apt_package_loop

- name: Install required pip packages
  pip:
    name: '{{ mysql_pip_package_loop.name }}'
    version: '{{ mysql_pip_package_loop.version|d(omit) }}'
  with_items: '{{ mysql_required_pip_packages }}'
  loop_control:
    loop_var: mysql_pip_package_loop

- name: Install trusty repo
  apt_repository:
    repo: 'deb http://archive.ubuntu.com/ubuntu trusty universe'
  when:
    - not mysql_use_percona
    - mysql_version == '5.6'
    - ansible_lsb.codename != 'trusty'

- name: Install percona repository packages
  apt:
    deb: '{{ mysql_percona_repository }}'
    update_cache: yes
