- name: Update mysql root password for all hosts
  mysql_user:
    name: 'root'
    host_all: 'yes'
    password: '{{ mysql_root_password }}'
    priv: '*.*:ALL,GRANT'

- name: Copy .my.cnf file with root credentials
  template:
    src: ".my.cnf.j2"
    dest: "/root/.my.cnf"
    owner: root
    group: root
    mode: 0600
  vars:
    mysql_mycnf_user: 'root'
    mysql_mycnf_pass: '{{ mysql_root_password }}'

- name: Remove anonymous MySQL users
  mysql_user:
    name: ""
    host_all: 'yes'
    state: absent

- name: Remove MySQL test database.
  mysql_db:
    name: 'test'
    state: 'absent'
